[package]
name = "potatodb-examples"
description = "Example programs demonstrating PotatoDB use cases"
version.workspace = true
edition.workspace = true
publish = false

[features]
default = ["use-mimalloc"]
use-mimalloc = ["dep:mimalloc"]
use-jemalloc = ["dep:tikv-jemallocator"]

[dependencies]
arrow.workspace = true
mimalloc = { workspace = true, optional = true }
tikv-jemallocator = { workspace = true, optional = true }
potatodb-engine.workspace = true
potatodb-display.workspace = true
potatodb-server.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tokio.workspace = true
