[package]
name = "potatodb-python"
description = "Python bindings for PotatoDB"
version.workspace = true
edition.workspace = true

[lib]
name = "potatodb_python"
crate-type = ["cdylib", "rlib"]

[dependencies]
arrow.workspace = true
futures.workspace = true
potatodb-engine.workspace = true
pyo3 = { version = "0.28.2", features = ["abi3-py39"] }
tokio.workspace = true
